# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='intrests',
            field=models.CharField(choices=[('art', 'ART'), ('reading', 'READING'), ('painting', 'PAINTING'), ('sports', 'SPORTS'), ('tech', 'TECH'), ('music', 'MUSIC'), ('traveling', 'TRAVELLING'), ('other', 'OTHER')], default='tech', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='maxAge',
            field=models.DecimalField(decimal_places=0, default=90, max_digits=100),
        ),
        migrations.AddField(
            model_name='product',
            name='minAge',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=100),
        ),
        migrations.AddField(
            model_name='product',
            name='occupation',
            field=models.CharField(default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='relation',
            field=models.CharField(choices=[('friend', 'FRIEND'), ('dad', 'DAD'), ('sister', 'SISTER'), ('mom', 'MOM'), ('boy friend', 'BOY FRIEND'), ('brother', 'BROTHER'), ('girl friend', 'GIRL FRIEND'), ('other', 'OTHER')], default='brother', max_length=6),
        ),
    ]
